export const SET_USER = "SET_USER";
export const SET_CURRENT_AUCTION = "SET_CURRENT_AUCTION";
export const SET_SHOW_MENU = "SET_SHOW_MENU";
export const SET_SHOW_CREATE = "SET_SHOW_CREATE";
export const SET_PLAYER_DATA = "SET_PLAYER_DATA";
export const LOG_OUT = "LOG_OUT";
export const SET_PLAYER_AUCTION_DATA = "SET_PLAYER_AUCTION_DATA";
